### ISSUE TITLE
Add WowClassic to the Process name list

### ISSUE THREAD

**Issue by biscuitboy-uk** [julianperrott/FishingFun#1]
Can you add "WowClassic" to the Process names list to make it work with Classic WoW!

Thanks.

**Comment by olaims** [comment]
Change this line inside WowProcess

var names = string.IsNullOrEmpty(name) ? new List<string> { "WowClassic", "Wow-64" } : new List<string> { name };

And it will work

**Comment by julianperrott** [comment]
Done
