### ISSUE TITLE
Mouse dragging window

### ISSUE THREAD

**Issue by mbless** [julianperrott/FishingFun#11]
Hi,

I'm having this issue with the mouse that drags the whole window to catch a fish. Maybe this issue is due to the time between the cursor movement and the right click. Maybe someone can point me in the code we it is written to go from initial position of the cursor to the bobber and do the right click.

**Comment by istyria** [comment]
same problem here ....but ...some month ago  bot worked

**Comment by julianperrott** [comment]
I think this is fixed now. I changed the way it clicks.

**Comment by DuncanFairley** [comment]
This still occurs for me using current master.
