### ISSUE TITLE
Looting Error

### ISSUE THREAD

**Issue by Corepoint043** [julianperrott/FishingFun#13]
Today, after maintenance on 07/22/2020, looting has not been functioning. The cursor will move to the bobber but gets teleported just before it loots to the top left corner of the screen and then returns to the bobber. The program was working fine for me the day before and I hadn't changed any settings. Behavior is consistent even after a fresh download and full system restart.

**Comment by snakestrike** [comment]
Also having the same issue, just want to say that this Is an excellent program and appreciate you sharing with us.

**Comment by CHATCHJ** [comment]
I am also have the looting error. It clicks the bobber but nothing is actually looted.

**Comment by CHATCHJ** [comment]
It seems after some testing the mouse is moving to the correct spot but the right click is not being recognized and the lure is just being recast.

**Comment by SalientAnimal** [comment]
I seem to be having the same issue

**Comment by liamcooper** [comment]
Hi guys, I also had this problem, I've made some changes to my version to get the right click working again, but you'll need to build it yourself.

The changes I made are in the /Source/GuyGotBot/Platform/WowProcess.cs file, you can see my version of the file here https://pastebin.com/3SsBuiHN

Hope this helps.

**Comment by julianperrott** [comment]
Hi, sorry it it has been broken for a while. Funny, but it still works for me as I used it yesterday.

Anyway, I have change the right clicking to use @liamcooper method. Please get the latest and let me know if it is fixed now.

**Comment by Veeshan1408** [comment]
Is there som way to delay the rightclick when it needs to click the bobber? Mine moves the screen abit when it wants to loot.
Rookie at coding, so excuse me if its a dumb question :)

**Comment by julianperrott** [comment]
Hi,

If you edit file Fishbot.cs (\Source\FishingFunBot\Bot\FishBot.cs) there is a method called Loot which looks like the code below, if you want a longer delay then change the Sleep(1500) to Sleep(3000), the number is milliseconds so 1500 is 1.5 seconds and 3000 would be 3 seconds.

    private void Loot(Point bobberPosition)
        {
            Sleep(1500);
            logger.Info($"Right clicking mouse to Loot.");
            WowProcess.RightClickMouse(logger, bobberPosition);
            Sleep(1000);
        }

**Comment by Shiinuz** [comment]
> Hi, If you edit file Fishbot.cs (\Source\FishingFunBot\Bot\FishBot.cs) there is a method called Loot which looks like the code below, if you want a longer delay then change the Sleep(1500) to Sleep(3000), the number is milliseconds so 1500 is 1.5 seconds and 3000 would be 3 seconds. private void Loot(Point bobberPosition) { Sleep(1500); logger.Info($"Right clicking mouse to Loot."); WowProcess.RightClickMouse(logger, bobberPosition); Sleep(1000); } From: Veeshan1408 <notifications@github.com> Sent: 09 August 2020 18:38 To: julianperrott/FishingFun <FishingFun@noreply.github.com> Cc: Julian Perrott <julian_perrott@hotmail.com>; Comment <comment@noreply.github.com> Subject: Re: [julianperrott/FishingFun] Looting Error (#13) Is there som way to delay the rightclick when it needs to click the bobber? Mine moves the screen abit when it wants to loot. Rookie at coding, so excuse me if its a dumb question :) — You are receiving this because you commented. Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjulianperrott%2FFishingFun%2Fissues%2F13%23issuecomment-671080270&data=02%7C01%7C%7Cd4d7d68d8c3b4cd122da08d83c8afd7f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637325914933131596&sdata=2NpyKg4hHgdieTuQnLsKpzbmU41XTjQ8e9c3rZ1Dxhk%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABR7ACDP6JTZRRGXWURJYF3R73NIJANCNFSM4PEJPQNA&data=02%7C01%7C%7Cd4d7d68d8c3b4cd122da08d83c8afd7f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637325914933141593&sdata=QNwMEDfKNIRDbseCbxef8M6kB%2B1Cl2DuFZAVKCylzp8%3D&reserved=0>.

Just can't find that juicy sweetspot.  Still moving screen 1 in 20 loots. 
I disabled all addons with fastloot, i do have autoloot without key modifier on & changed the sleep value after the loot to 3000ms to give it some time between casts. Tried messing around with the sleep value before the cast, but just can't get it right. What am i doing wrong? 

thanks in advance

**Comment by Shiinuz** [comment]
I just can't find that juicy sweetspot. Still moving screen 1 in 20 loots.
I disabled all addons with fastloot, i do have autoloot without key modifier on & changed the sleep value after the loot to 3000ms to give it some time between casts. Tried messing around with the sleep value before the cast (from 1000-3000 in steps of 100), but just can't get it right. What am i doing wrong? Is there anyway to code a security to not change the camera view?

thanks in advance

**Comment by julianperrott** [comment]
The screen probably moves because the mouse position is moved when the mouse button is down.

` public static void RightClickMouse_LiamCooper(ILog logger, System.Drawing.Point position)
        {
            var activeProcess = GetActiveProcess();
            var wowProcess = WowProcess.Get();
            if (wowProcess != null)
            {
                var oldPosition = System.Windows.Forms.Cursor.Position;

                System.Windows.Forms.Cursor.Position = position;
                mouse_event((int)MouseEventFlags.RightDown, position.X, position.Y, 0, 0);
                Thread.Sleep(30 + random.Next(0, 47));
                mouse_event((int)MouseEventFlags.RightUp, position.X, position.Y, 0, 0);
                RefocusOnOldScreen(logger, activeProcess, wowProcess, oldPosition);
            }
        }`

I assume the method above is the right click you are using ?

Try adding a delay after System.Windows.Forms.Cursor.Position = position

Or perhaps move the mouse position to the position, using either:
`SetCursorPos(position.X, position.Y);`
or
`for (int i = 20; i > 0; i--)
                {
                    SetCursorPos(position.X + i, position.Y + i);
                    Thread.Sleep(1);
                }`

include a little delay after, then call the mouse_event((int)MouseEventFlags.RightDown, position.X, position.Y, 0, 0);

or perhaps the RefocusOnOldScreen is messing things up ?

It is hard to fix when I don't see the issue. Good  luck.

**Comment by Shiinuz** [comment]
Mate, you're a hero!

        public static void RightClickMouse_LiamCooper(ILog logger, System.Drawing.Point position)
        {
            var activeProcess = GetActiveProcess();
            var wowProcess = WowProcess.Get();
            if (wowProcess != null)
            {
                var oldPosition = System.Windows.Forms.Cursor.Position;

                System.Windows.Forms.Cursor.Position = position;
                Thread.Sleep(1000);
                mouse_event((int)MouseEventFlags.RightDown, position.X, position.Y, 0, 0);
                Thread.Sleep(30 + random.Next(0, 47));
                mouse_event((int)MouseEventFlags.RightUp, position.X, position.Y, 0, 0);
                RefocusOnOldScreen(logger, activeProcess, wowProcess, oldPosition);
            }
        }

Adding a delay before the rightclick fixed my issue. 
Thank you very much. <3

**Comment by julianperrott** [comment]
Add a delay to right click.
