### ISSUE TITLE
Spell Casting When Running

### ISSUE THREAD

**Issue by Nevicar** [julianperrott/FishingFun#14]
Heyo,

First off, absolutely excellent program. This really is great what you've done here.

Only one issue - whenever I start this it casts a spell on my bars, Wake of Ashes - is this intended or is there a way to troubleshoot this? I have moved it from it's original spot off my bars, so it seems to be casting it somehow.

Edit: Looks like its when it does "Pressing key System.Collections.Generic.List'1[System.ConsoleKey] to run a macro." I took the spell off my bars and it stopped casting it.

**Comment by krk830** [comment]
that's a feature. I've got fishing on 4, the Lure on 5 and the pole on 6 and it automatically reapplies the lure whenever it runs out...

**Comment by Nevicar** [comment]
Ahhh, makes sense, sweet thanks.

**Comment by julianperrott** [comment]
In Program.cs line 23:
`var bot = new FishingBot(bobberFinder, biteWatcher, ConsoleKey.D4, new List<ConsoleKey> { ConsoleKey.D5 });`

The List is a parameter called tenMinKey, which get clicked, every... wait for it... 10 minutes. So if you don't want to have it clicked then remove the key from the list. I use D5 to run a macro to delete the junk fish.
