### ISSUE TITLE
classic colour adjustment

### ISSUE THREAD

**Issue by krk830** [julianperrott/FishingFun#15]
Is someone using the bot in classic wow?
the bot works awesome in zones like feralas, where there's no red.
I have troubles adjusting the colours for Azshara or the Plaguelands. 
There is too much red in the configuration or the bobber cant be detected.
If someone figured that out, pls share

thanks

**Comment by julianperrott** [comment]
My advice is don't fish in those areas. Stone Scale Eels, Firefin snapper are the only fish I don't throw away.  What fish are you trying to catch ?

**Comment by krk830** [comment]
Nightfin, Lobster and the season for Squid starts soon.
It's not that important you're right,
thank you for sharing your work!
