### ISSUE TITLE
ui stuck when press start

### ISSUE THREAD

**Issue by b33bb** [julianperrott/FishingFun#16]
Hi!
I use it for a long time like maybe 2 or 3 weeks and has no problem bot recently i got a problem.
When i press start its frezee and do nothing before i stop debugging. 
Console version works fine before, but after that its stop casting and starts dragging camera up af after looting.
ddnt touch anythin please help

**Comment by julianperrott** [comment]
Try commenting out or removing this line in WowProcess.cs in method RightClickMouse_LiamCooper around line 170.

`RefocusOnOldScreen(logger, activeProcess, wowProcess, oldPosition);`
