### ISSUE TITLE
Failed to find the wow process

### ISSUE THREAD

**Issue by Kiahhhh** [julianperrott/FishingFun#18]
When I start the bot, the log says this:

''Failed to find the wow process, tried: Wow, WowClassic, Wow-64''

and my wow process name is WoW.
I tried add the name WoW to the WowProcess.cs but nothings happend.
The bot detects the bobber but it does not automatically pull it (even if it has the letter correctly assigned) not does it loot it, I suppose it is due to that same issue.

**Comment by julianperrott** [comment]
Bring up task manager and go to the details tab, what is the name of the wow process?

**Comment by Kiahhhh** [comment]
The name is "WoW.exe"
I play in a wow private server 8.3

**Comment by julianperrott** [comment]
Looks like it a case issue. WoW.exe vs Wow.exe.

**Comment by Kiahhhh** [comment]
If the program searches for the process exactly, there's no way it will search for WoW.exe instead of Wow.exe?

**Comment by julianperrott** [comment]
Get the latest code and let me know if this fixes the problem.

**Comment by Kiahhhh** [comment]
Thanks man this work so good now :D
