### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by olaims** [julianperrott/FishingFun#2]
It was working till yesterday, now I get the exception on the log text

![image](https://user-images.githubusercontent.com/27026293/70639791-47b65000-1c3b-11ea-93cb-ddc756696435.png)

**Comment by olaims** [comment]
Ok I changed following line and now it works :)

            var names = string.IsNullOrEmpty(name) ? new List<string> { "**WowClassic**", "Wow-64" } : new List<string> { name };

**Comment by Moonzy123** [comment]
Hey, I mailed you about this issue: how do you change that line? I'd like to fix it too as I get the same issue.

**Comment by Moonzy123** [comment]
Nvm I found the location and edited the line myself but the issue remains. It says:

System.NullReferenceException: De objectverwijzing is niet op een exemplaar van een object ingesteld.
   bij FishingFun.WowProcess.KeyDown(ConsoleKey key)
   bij FishingFun.WowProcess.PressKey(ConsoleKey key)
   bij FishingFun.FishingBot.Start()

Which translates to:

The objectreferall has been put on an example of an object, at 
FishingFun.Wowprocess.Keydown 
(etc)

how to fix?

**Comment by julianperrott** [comment]
The issue was that the wow process name changed. I have fixed it in the code and the zip.
