### ISSUE TITLE
Tenminkey/macro key

### ISSUE THREAD

**Issue by Pendorax** [julianperrott/FishingFun#24]
anyone that call tell me how to switch the keybind on my Tenminkey/macro key?

it doesnt seem to be bound to anything and will cast some random ability depending on wich class i am on Eg. it cast "altar time" on my Frost Mage.

the log says this:
Pressing key System.Collections.Generic.List`1[System.ConsoleKey] to run a macro.

**Comment by liamcooper** [comment]
If you use the interface, by default it presses characters 5 and 6.
If you use the console, be default it presses character 5.

I don't think there's a way to change it with the ui, it's hard coded, I run it through an IDE and change it manually.

**Comment by Pendorax** [comment]
@liamcooper ok thanks, any chance you could tell me where in the code i can change it? i have looked for ages and cant seem to find it

**Comment by liamcooper** [comment]
Sure,

For UI, Source/FishingFunUI/UI/MainWindow.xaml.cs line 167
For console, Source/FishingFunConsole/Program.cs line 30

**Comment by Pendorax** [comment]
@liamcooper Thanks you are a lifesaver!
