### ISSUE TITLE
Virus in zip file

### ISSUE THREAD

**Issue by billykwooten** [julianperrott/FishingFun#5]
There's a Trojan in https://github.com/julianperrott/FishingFun/raw/master/FishingFun.zip

Seems this package is importing a virus, all virus detection scans showing a password keylogger trojan horse.

**Comment by petrvecera** [comment]
It's most likely a fake positive. But it's little bit fishy, this is scan of the committed zip file:
https://www.virustotal.com/gui/file/134c35acf3ed5da4806224945b1fafd7e78a41d8dcc694fdf78c86de41e85f37/detection

And this is scan of debug build from the source code:
https://www.virustotal.com/gui/file/8504af6a5051119273f53cb85c77226849f6feb8025aef8006ac52ca82fadab5/detection

I think it's save to download the source code and do the own build.

**Comment by julianperrott** [comment]
I have deleted the zip to avoid any confusion. I think the AV may be picking up on the name of the exe being 'Chrome'.
