### ISSUE TITLE
Teamviewer

### ISSUE THREAD

**Issue by Misspackrat** [julianperrott/FishingFun#6]
Hello, I was thinking of running this on my laptop and teamview into my home computer. The home computer would be running the wow classic, being controlled by my laptop. Obviously with how this is coded now, it will not work as it looks for wow classic window to be active. How would I change this to be teamviewer window active, then inside that look for the wow window? Can this be done? 

thank you, Newb

**Comment by julianperrott** [comment]
The bot needs to be running on the same PC, sorry.
