### ISSUE TITLE
Right click randomized location

### ISSUE THREAD

**Issue by Misspackrat** [julianperrott/FishingFun#7]
Would it be beneficial to randomize the right click location to a little up at times and a little right at times, so the right click would not be on the same part of the bobber every time? Or is this already doing so? I am pretty sure I saw the click after detect bobber movement is randomized, so that is great.

**Comment by julianperrott** [comment]
The bobber moves each cast, so you are not always clicking on the same part of the screen. I doubt the client would record where on the bobber you click, so you could add a random offset to where it clicks, but I don't think that it is needed.
