### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by yungollie** [julianperrott/FishingFun#8]
Could not find file 'C:\Users\Ollie\Documents\FishingFun-master\FishingFun-master\Source\bin\Debug\log4net.config'.'
This exception was originally thrown at this call stack:
    [External Code]
    FishingFun.App.App() in App.xaml.cs

Can't get this to work or make sense of the readme 

take this as an idiot using the program, pls explain lol

**Comment by wewerak47** [comment]
I also run into this problem. I just changed the .config to .xml because log4net.xml was in the build result.

**Comment by julianperrott** [comment]
Is this still an issue, is anyone else getting this ?

**Comment by CHATCHJ** [comment]
Hello I am still getting this issue but verified the file is there :(

**Comment by julianperrott** [comment]
If you have this issue, please comment in here.

To solve, find the file log4net.config (found in the root of the source folder) and copy into the bin\debug folder.

**Comment by julianperrott** [comment]
Hi, could you try this…

Find the file log4net.config (found in the root of the source folder) and copy into the bin\debug folder.

Regards,
Julian.

**Comment by julianperrott** [comment]
Hopefully this is fixed now.
