### ISSUE TITLE
False Positive --> Trojan.PasswordStealer.MSIL

### ISSUE THREAD

**Issue by IoanAnev** [julianperrott/FishingFun#9]
While running under Visual Studio FishingFun.UI, MalwareBytes detects ..\bin\Release\Chrome.exe as a Trojan.PasswordStealer.MSIL. The console application works well though, but when it comes to adjusting the redness, there is no option...

Any workaround to this issue without disabling MalwareBytes?

**Comment by julianperrott** [comment]
You could try naming the exe something else.
